import React, { useState, useEffect } from 'react';
import { Camera, Settings, Key, Wand2, ArrowRight, Video, Sparkles, AlertCircle, Save, RefreshCw, Clock, ChevronRight, Trash2, Menu } from 'lucide-react';
import { generateDescription } from './lib/ai';
import { db } from './lib/firebase';
import { collection, doc, setDoc, getDocs, deleteDoc, query, orderBy, onSnapshot } from 'firebase/firestore';
import ReactMarkdown from 'react-markdown';
import './index.css';

function App() {
  const [engineStatus, setEngineStatus] = useState('Standby');
  const [showMobileSidebar, setShowMobileSidebar] = useState(false);
  const [genMode, setGenMode] = useState('concise'); // 'concise' or 'detailed'

  // Detect if running in a Chrome Extension context (Side Panel / Popup)
  const isExtension = typeof chrome !== 'undefined' && !!chrome.runtime && !!chrome.runtime.id;

  // Input States
  const [productName, setProductName] = useState('');
  const [materials, setMaterials] = useState('');
  const [references, setReferences] = useState('');
  const [files, setFiles] = useState([]);

  // Execution States
  const [isGenerating, setIsGenerating] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');

  // History States
  const [history, setHistory] = useState([]);
  const [isHistoryLoaded, setIsHistoryLoaded] = useState(false);
  const [activeHistoryId, setActiveHistoryId] = useState(null);
  const [activeVersionId, setActiveVersionId] = useState(null);

  // Extension Logic: Listen for scraped data from Shopify page (only in extension mode)
  useEffect(() => {
    if (isExtension && chrome.runtime && chrome.runtime.onMessage) {
      const messageListener = (request) => {
        if (request.action === "PRODUCT_DATA_SCRAPED") {
          setProductName(request.data.title);
        }
      };
      chrome.runtime.onMessage.addListener(messageListener);
      return () => chrome.runtime.onMessage.removeListener(messageListener);
    }
  }, []);

  const applyToShopify = () => {
    if (!result) return;
    
    const sectionsHtml = result.sections && result.sections.length > 0 
      ? result.sections.map(s => `
          <div class="product-section" style="margin-bottom: 20px;">
            <h4 style="margin-bottom: 8px; color: #333;">${s.heading}</h4>
            <p style="line-height: 1.6;">${s.content.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}</p>
          </div>
        `).join('')
      : '';

    const descriptionHtml = `
      <div class="product-description-ai" style="font-family: inherit;">
        <div class="overview" style="margin-bottom: 20px; font-size: 1.1em; line-height: 1.6;">
          ${result.overview.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}
        </div>
        
        ${sectionsHtml}
        
        <h3 style="margin-top: 24px; margin-bottom: 12px; border-bottom: 1px solid #eee; padding-bottom: 4px;">Key Features:</h3>
        <ul style="padding-left: 20px;">
          ${result.features.map(f => `
            <li style="margin-bottom: 8px; line-height: 1.5;">
              ${f.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')}
            </li>
          `).join('')}
        </ul>
        
        <p style="margin-top: 32px; font-size: 0.85em; color: #888; font-style: italic; border-top: 1px dashed #eee; padding-top: 12px;">
          * Professional description generated by CineGear MiniMax AI
        </p>
      </div>
    `;

    if (isExtension && chrome.tabs) {
      chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
        if (tabs[0]) {
          chrome.tabs.sendMessage(tabs[0].id, {
            action: "APPLY_TO_SHOPIFY",
            data: {
              title: result.title,
              description: descriptionHtml
            }
          });
        }
      });
    }
  };

  useEffect(() => {
    const historyRef = collection(db, "history");
    const q = query(historyRef, orderBy("lastUpdated", "desc"));
    
    // Use onSnapshot for real-time collaboration across all team members
    const unsubscribe = onSnapshot(q, (snapshot) => {
      const historyData = snapshot.docs.map(doc => doc.data());
      setHistory(historyData);
      setIsHistoryLoaded(true);
    }, (err) => {
      console.error("Firebase Real-time Sync Error:", err);
      setIsHistoryLoaded(true);
    });

    return () => unsubscribe();
  }, []);

  const handleFileUpload = (e) => {
    const selectedFiles = Array.from(e.target.files);
    const totalSize = selectedFiles.reduce((acc, file) => acc + file.size, 0);
    if (totalSize > 20 * 1024 * 1024) {
      setError("Total file size exceeds 20MB limit.");
      return;
    }
    setFiles(prev => [...prev, ...selectedFiles].slice(0, 5));
  };

  const removeFile = (index) => {
    setFiles(prev => prev.filter((_, i) => i !== index));
  };

  const handleGenerate = async () => {
    if (!productName.trim()) {
      setError('Product Name is required.');
      return;
    }
    if (!materials.trim() && files.length === 0) {
      setError('Product materials or files are required.');
      return;
    }

    setError('');
    setIsGenerating(true);

    try {
      const processedFiles = [];
      for (const file of files) {
        const reader = new FileReader();
        const base64Promise = new Promise((resolve, reject) => {
          reader.readAsDataURL(file);
          reader.onload = () => resolve({
            base64: reader.result.split(',')[1],
            mimeType: file.type
          });
          reader.onerror = reject;
        });
        processedFiles.push(await base64Promise);
      }

      const combinedMaterials = `Product Name Concept: ${productName}\n---\n${materials}`;
      const outputJson = await generateDescription(combinedMaterials, references, processedFiles, setEngineStatus, genMode);
      setResult(outputJson);
      setEngineStatus('Success');
    } catch (err) {
      setError(err.message);
      setEngineStatus('Failed');
    } finally {
      setIsGenerating(false);
    }
  };

  const saveToHistory = async () => {
    if (!result || !productName) return;
    const newVersion = {
      id: Date.now().toString(),
      result: result,
      timestamp: new Date().toISOString()
    };

    let updatedHistoryList = [...history];
    const existingIdx = updatedHistoryList.findIndex(h => h.productName.toLowerCase() === productName.trim().toLowerCase());
    let productToSave = null;

    if (existingIdx >= 0) {
      productToSave = {
        ...updatedHistoryList[existingIdx],
        versions: [newVersion, ...updatedHistoryList[existingIdx].versions],
        lastUpdated: newVersion.timestamp
      };
      updatedHistoryList[existingIdx] = productToSave;
    } else {
      productToSave = {
        id: Date.now().toString() + "-prod",
        productName: productName.trim(),
        versions: [newVersion],
        lastUpdated: newVersion.timestamp
      };
      updatedHistoryList = [productToSave, ...updatedHistoryList];
    }

    try {
      await setDoc(doc(db, "history", productToSave.id), productToSave);
      setHistory(updatedHistoryList);
      setActiveHistoryId(productToSave.id);
      setActiveVersionId(newVersion.id);
      setResult(null);
    } catch (err) {
      console.error("Failed to save to Firebase:", err);
    }
  };

  const loadHistoryItem = (historyId, versionId) => {
    const prod = history.find(h => h.id === historyId);
    if (!prod) return;
    const ver = prod.versions.find(v => v.id === versionId) || prod.versions[0];
    setActiveHistoryId(historyId);
    setActiveVersionId(ver.id);
    setProductName(prod.productName);
    setResult(ver.result);
    setShowMobileSidebar(false);
  };

  const deleteHistoryProduct = async (e, productId) => {
    e.stopPropagation();
    try {
      await deleteDoc(doc(db, "history", productId));
      setHistory(prev => prev.filter(h => h.id !== productId));
      if (activeHistoryId === productId) startNew();
    } catch (err) {
      console.error("Failed to delete product:", err);
    }
  };

  const deleteHistoryVersion = async (e, productId, versionId) => {
    e.stopPropagation();
    const prodIdx = history.findIndex(h => h.id === productId);
    if (prodIdx < 0) return;

    let productToUpdate = { ...history[prodIdx] };
    productToUpdate.versions = productToUpdate.versions.filter(v => v.id !== versionId);

    try {
      if (productToUpdate.versions.length === 0) {
        await deleteDoc(doc(db, "history", productId));
        setHistory(prev => prev.filter(h => h.id !== productId));
        if (activeHistoryId === productId) startNew();
      } else {
        productToUpdate.lastUpdated = productToUpdate.versions[0].timestamp;
        await setDoc(doc(db, "history", productId), productToUpdate);
        let newHistory = [...history];
        newHistory[prodIdx] = productToUpdate;
        setHistory(newHistory);
        if (activeHistoryId === productId && activeVersionId === versionId) {
          loadHistoryItem(productId, productToUpdate.versions[0].id);
        }
      }
    } catch (err) {
      console.error("Failed to delete version:", err);
    }
  };

  const startNew = () => {
    setActiveHistoryId(null);
    setActiveVersionId(null);
    setResult(null);
    setProductName('');
    setMaterials('');
    setReferences('');
    setFiles([]);
  };

  return (
    <div className="app-container">
      <header className="app-header">
        <div className="header-left">
          <button onClick={() => setShowMobileSidebar(true)} className="sidebar-toggle">
            <Menu size={24} />
          </button>
          <h1 className="header-title">
            Shopify <span className="text-gradient">MiniMax AI</span>
          </h1>
        </div>
        <div className="engine-status">
          <span className="status-dot" style={{ background: isGenerating ? 'var(--accent-color)' : 'var(--success-color, #10b981)' }} />
          {engineStatus}
        </div>
      </header>

      <div className={`mobile-overlay ${showMobileSidebar ? 'visible' : ''}`} onClick={() => setShowMobileSidebar(false)} />

      <div className="main-layout">
        <div className={`sidebar-panel ${showMobileSidebar ? 'mobile-open' : ''}`}>
          <aside className="sidebar">
            <div className="brand-section">
              <div className="brand-icon">
                <Camera color="white" size={20} />
              </div>
              <div className="brand-text">
                <h1>Product Content <div className="text-gradient">Generator</div></h1>
                <span>By CineGearPro</span>
              </div>
            </div>

            <button onClick={startNew} className="new-btn">
              <Sparkles size={16} /> New Description
            </button>

            <div className="history-label">History Vault</div>
            <div className="history-list">
              {history.length === 0 ? (
                <p className="no-history">No history yet.</p>
              ) : (
                history.map(prod => (
                  <div key={prod.id} className="history-group">
                    <div className={`history-item ${activeHistoryId === prod.id ? 'active' : ''}`} onClick={() => loadHistoryItem(prod.id, prod.versions[0].id)}>
                      <div className="history-header">
                        <div className="history-title">{prod.productName}</div>
                        <button onClick={(e) => deleteHistoryProduct(e, prod.id)} className="delete-btn"><Trash2 size={14} /></button>
                      </div>
                      <div className="history-meta">
                        <Clock size={12} /> {new Date(prod.lastUpdated).toLocaleDateString()} | {prod.versions.length} ver
                      </div>
                    </div>
                    {activeHistoryId === prod.id && prod.versions.length > 1 && (
                      <div className="version-list">
                        {prod.versions.map((ver, idx) => (
                          <div key={ver.id} className="version-item" onClick={() => loadHistoryItem(prod.id, ver.id)}>
                            <div className={activeVersionId === ver.id ? 'active-ver' : ''}>
                              <ChevronRight size={12} /> Version {prod.versions.length - idx}
                            </div>
                            <button onClick={(e) => deleteHistoryVersion(e, prod.id, ver.id)} className="delete-btn-sm"><Trash2 size={12} /></button>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                ))
              )}
            </div>
          </aside>
        </div>

        <div className="content-panel">
          <main className="main-container">
            <div className="input-section">
              <div className="glass-panel input-card">
                <label><Camera size={18} color="var(--accent-color)" /> Product Name</label>
                <input type="text" value={productName} onChange={(e) => setProductName(e.target.value)} placeholder="e.g. Arri Alexa 35" />
              </div>

              <div className="glass-panel input-card">
                <label><Video size={18} color="var(--accent-color)" /> Materials</label>
                <textarea value={materials} onChange={(e) => setMaterials(e.target.value)} placeholder="Paste specs here..." />
                
                <div className="file-upload">
                  <input type="file" multiple onChange={handleFileUpload} accept="image/*,.pdf,.doc,.docx,.txt" />
                  <p>Drop files here (max 20MB)</p>
                </div>

                {files.length > 0 && (
                  <div className="file-list">
                    {files.map((file, idx) => (
                      <div key={idx} className="file-item">
                        <span>{file.name}</span>
                        <button onClick={() => removeFile(idx)}>×</button>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {error && <div className="error-alert"><AlertCircle size={20} /><span>{error}</span></div>}

              <div className="mode-selector">
                <button 
                  onClick={() => setGenMode('concise')} 
                  className={`mode-btn ${genMode === 'concise' ? 'active' : ''}`}
                >
                  Concise
                </button>
                <button 
                  onClick={() => setGenMode('detailed')} 
                  className={`mode-btn ${genMode === 'detailed' ? 'active' : ''}`}
                >
                  Detailed
                </button>
              </div>

              <button onClick={handleGenerate} disabled={isGenerating} className="generate-btn">
                {isGenerating ? 'Synthesizing...' : `Generate ${genMode === 'detailed' ? 'Detailed' : 'Concise'} Description`}
              </button>
            </div>

            <div className="output-section">
              <div className="glass-panel output-card">
                <div className="output-header">
                  <h3><ArrowRight color="var(--accent-color)" /> Result</h3>
                  {result && (
                    <div className="action-btns">
                      {isExtension && (
                        <button onClick={applyToShopify} className="apply-btn">
                          <ArrowRight size={14} /> Apply to Shopify
                        </button>
                      )}
                      <button onClick={saveToHistory} className="save-btn"><Save size={14} /> Save to Vault</button>
                    </div>
                  )}
                </div>

                {result ? (
                  <div className="result-content">
                    <div className="result-field">
                      <div className="field-label">Title</div>
                      <h2 className="field-value">{result.title}</h2>
                    </div>
                    <div className="result-field">
                      <div className="field-label">Overview</div>
                      <div className="markdown-body">
                        <ReactMarkdown>{result.overview}</ReactMarkdown>
                      </div>
                    </div>

                    {result.sections && result.sections.map((section, idx) => (
                      <div key={idx} className="result-field">
                        <div className="field-label">{section.heading}</div>
                        <div className="markdown-body">
                          <ReactMarkdown>{section.content}</ReactMarkdown>
                        </div>
                      </div>
                    ))}

                    <div className="result-field">
                      <div className="field-label">Features</div>
                      <ul>
                        {result.features?.map((f, i) => (
                          <li key={i} className="markdown-body">
                            <ReactMarkdown>{f}</ReactMarkdown>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                ) : (
                  <div className="empty-state">
                    <Wand2 size={48} />
                    <p>AI description will appear here.</p>
                  </div>
                )}
              </div>
            </div>
          </main>
        </div>
      </div>
    </div>
  );
}

export default App;
